timeout: 3

/MayOS
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/boot/disk.img

/MayOS (safe graphics)
    comment: Use the firmware's screen instead of MayOS's display drivers.
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/boot/disk.img
    cmdline: safegraphics
