[package]
name = "mayos-kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
fat32 = { path = "../libs/fat32" }
gfx = { path = "../libs/gfx" }
net = { path = "../libs/net" }
image = { path = "../libs/image" }
media = { path = "../libs/media" }
embedded-tls = { version = "0.19", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
rand_core = "0.6"
embedded-io = { version = "0.7", default-features = false }
web = { version = "0.1.0", path = "../libs/web" }
libm = "0.2.16"
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }
ab_glyph = { version = "0.2.32", default-features = false, features = ["libm"] }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
opt-level = 3
debug = true
codegen-units = 1

[workspace]
