#!/usr/bin/env python3
"""Generate libs/media/src/tables.rs from the constant tables printed in the
H.264, AAC and MP3 standards. The numbers are taken from FFmpeg's copies of
those tables (fetched into a reference directory); only data is used.

usage: gen_media_tables.py <reference dir> <out.rs>
"""
import re, sys

REF, OUT = sys.argv[1], sys.argv[2]


def src(name):
    text = open(f"{REF}/{name}").read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse_nested(body, pos=0):
    """Parse a C brace initializer into nested lists of ints."""
    assert body[pos] == "{"
    pos += 1
    items = []
    while True:
        m = re.compile(r"\s*,?\s*").match(body, pos)
        pos = m.end()
        if body[pos] == "}":
            return items, pos + 1
        if body[pos] == "{":
            sub, pos = parse_nested(body, pos)
            items.append(sub)
        else:
            m = re.compile(r"-?(?:0x[0-9a-fA-F]+|\d+)").match(body, pos)
            assert m, body[pos:pos + 30]
            items.append(int(m.group(0), 0))
            pos = m.end()


def flatten(items, dims):
    if not dims:
        return [items] if isinstance(items, int) else list(items)
    if items and isinstance(items[0], int) and len(dims) > 1:
        # A flat initializer for a multi-dimensional array.
        total = 1
        for d in dims:
            total *= d
        return items + [0] * (total - len(items))
    out = []
    for k in range(dims[0]):
        if k < len(items):
            v = items[k]
            if isinstance(v, int):
                out.append(v)
            else:
                out += flatten(v, dims[1:])
        else:
            sub = 1
            for d in dims[1:]:
                sub *= d
            out += [0] * sub
    return out


def array(file, name):
    s = src(file)
    m = re.search(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"\)?\s*((?:\[[^\]]*\])*)\s*=\s*\{", s)
    assert m, name
    dims = []
    for d in re.findall(r"\[([^\]]*)\]", m.group(1)):
        try:
            dims.append(int(eval(d)))
        except Exception:
            dims.append(None)
    items, _ = parse_nested(s, m.end() - 1)
    if not dims or dims[0] is None:
        if len(dims) <= 1:
            return flatten(items, [])
        dims[0] = len(items)
    return flatten(items, dims)


out = ["// Generated by tools/gen_media_tables.py. Do not edit.", "#![allow(clippy::all)]", ""]


def emit(name, ty, vals, per=16):
    out.append(f"pub static {name}: [{ty}; {len(vals)}] = [")
    for k in range(0, len(vals), per):
        out.append("    " + ", ".join(str(v) for v in vals[k:k + per]) + ",")
    out.append("];")
    out.append("")


# ---- H.264 ------------------------------------------------------------
ci = array("h264_cabac.c", "cabac_context_init_I")
cpb = array("h264_cabac.c", "cabac_context_init_PB")
assert len(ci) == 2048 and len(cpb) == 3 * 2048
N = 460
init = []
for t in range(4):
    tab = ci if t == 0 else cpb[(t - 1) * 2048:t * 2048]
    init += tab[:N * 2]
emit("CABAC_INIT", "i8", init)  # [idc+1 (0 = I)][ctx][m, n]

packed = array("cabac.c", "ff_h264_cabac_tables")
lps = [[packed[512 + q * 128 + s * 2] & 0xff for q in range(4)] for s in range(64)]
emit("CABAC_RANGE_LPS", "u8", [v for row in lps for v in row])
mlps = packed[512 + 4 * 128: 512 + 4 * 128 + 256]
# mlps_state[128 + state*2+mps] = next state after MPS; [127 - (state*2+mps)] after LPS.
trans_lps = [mlps[127 - s * 2] >> 1 for s in range(64)]
trans_mps = [mlps[128 + s * 2] >> 1 for s in range(64)]
emit("CABAC_TRANS_LPS", "u8", trans_lps)
emit("CABAC_TRANS_MPS", "u8", trans_mps)
emit("LAST_COEFF_OFFSET_8X8", "u8", packed[512 + 4 * 128 + 256:512 + 4 * 128 + 256 + 63])
sig8 = array("h264_cabac.c", "significant_coeff_flag_offset_8x8")
emit("SIG_COEFF_OFFSET_8X8", "u8", sig8[:63])

for name in ["coeff_token_len", "coeff_token_bits", "chroma_dc_coeff_token_len", "chroma_dc_coeff_token_bits",
             "total_zeros_len", "total_zeros_bits", "chroma_dc_total_zeros_len", "chroma_dc_total_zeros_bits",
             "run_len", "run_bits"]:
    emit(name.upper(), "u8", array("h264_cavlc.c", name))
emit("GOLOMB_TO_INTRA_CBP", "u8", array("h264data.c", "ff_h264_golomb_to_intra4x4_cbp"))
emit("GOLOMB_TO_INTER_CBP", "u8", array("h264data.c", "ff_h264_golomb_to_inter_cbp"))
emit("DEFAULT_SCALING4", "u8", array("h264_ps.c", "default_scaling4"))
emit("DEFAULT_SCALING8", "u8", array("h264_ps.c", "default_scaling8"))
alpha = array("h264_loopfilter.c", "alpha_table")
beta = array("h264_loopfilter.c", "beta_table")
tc0 = array("h264_loopfilter.c", "tc0_table")
# The tables are padded with 52 entries on each side; keep indexA 0..51.
emit("DEBLOCK_ALPHA", "u8", alpha[52:104])
emit("DEBLOCK_BETA", "u8", beta[52:104])
emit("DEBLOCK_TC0", "u8", [tc0[(52 + q) * 4 + b] for q in range(52) for b in range(1, 4)])

# ---- AAC --------------------------------------------------------------
emit("AAC_SF_CODES", "u32", array("aactab.c", "ff_aac_scalefactor_code"))
emit("AAC_SF_BITS", "u8", array("aactab.c", "ff_aac_scalefactor_bits"))
for i in range(1, 12):
    emit(f"AAC_CODES{i}", "u16", array("aactab.c", f"codes{i}"))
    emit(f"AAC_BITS{i}", "u8", array("aactab.c", f"bits{i}"))
for n in ["1024_96", "1024_64", "1024_48", "1024_32", "1024_24", "1024_16", "1024_8",
          "128_96", "128_48", "128_24", "128_16", "128_8"]:
    emit(f"AAC_SWB_{n}", "u16", array("aactab.c", f"swb_offset_{n}"))
emit("AAC_TNS_MAX_BANDS_1024", "u8", array("aactab.c", "ff_tns_max_bands_1024"))
emit("AAC_TNS_MAX_BANDS_128", "u8", array("aactab.c", "ff_tns_max_bands_128"))

# ---- MP3 --------------------------------------------------------------
emit("MP3_HUFF_LENS", "u8", array("mpegaudiodec_common.c", "mpa_hufflens"))
emit("MP3_HUFF_SYMS", "u8", array("mpegaudiodec_common.c", "mpa_huffsymbols"))
emit("MP3_HUFF_SIZES_M1", "u8", array("mpegaudiodec_common.c", "mpa_huff_sizes_minus_one"))
emit("MP3_HUFF_DATA", "u8", array("mpegaudiodec_common.c", "ff_mpa_huff_data"))
emit("MP3_QUAD_CODES", "u8", array("mpegaudiodec_common.c", "mpa_quad_codes"))
emit("MP3_QUAD_BITS", "u8", array("mpegaudiodec_common.c", "mpa_quad_bits"))
emit("MP3_BAND_SIZE_LONG", "u8", array("mpegaudiodec_common.c", "ff_band_size_long"))
emit("MP3_BAND_SIZE_SHORT", "u8", array("mpegaudiodec_common.c", "ff_band_size_short"))
emit("MP3_PRETAB", "u8", array("mpegaudiodec_common.c", "ff_mpa_pretab")[:22])
emit("MP3_SLEN", "u8", array("mpegaudiodec_common.c", "ff_slen_table"))
emit("MP3_LSF_NSF", "u8", array("mpegaudiodec_common.c", "ff_lsf_nsf_table"))

open(OUT, "w").write("\n".join(out))
print("wrote", OUT)
